CREATE DATABASE DB_JVT;
USE DB_JVT;
/*管理員表*/
CREATE TABLE `DT_ADMIN` (
  `ID` varchar(36) NOT NULL COMMENT '主键ID',
  `CODE` varchar(50) DEFAULT NULL COMMENT '编码 or 账号',
  `NAME` varchar(50) DEFAULT NULL COMMENT '名称',
  `PWD` varchar(2000) DEFAULT NULL COMMENT '密码',
  `SALT` varchar(8) DEFAULT NULL COMMENT '加密盐',
  `EMAIL` varchar(50) DEFAULT NULL COMMENT '邮箱',
  `STATE` int(11) DEFAULT NULL,
  `SORT` int(11) DEFAULT NULL,
  `ADD_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='管理员';

/*菜單表*/
CREATE TABLE `DT_MENU` (
  `ID` varchar(36) NOT NULL COMMENT '主键ID',
  `CODE` varchar(50) DEFAULT NULL COMMENT '编码',
  `NAME` varchar(50) DEFAULT NULL COMMENT '名称',
  `HAS_ICON` int DEFAULT NULL COMMENT '是否启用图标',
  `ICON_URL` varchar(2083) DEFAULT NULL COMMENT '图标路径',
  `URL` varchar(2083) DEFAULT NULL COMMENT '菜单路径',
  `PID` varchar(36) DEFAULT '0' COMMENT '父节点ID',
  `STATE` int(11) DEFAULT NULL,
  `SORT` int(11) DEFAULT NULL,
  `ADD_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='菜单';

/*任務調度表*/
CREATE TABLE DT_SCHEDULE_TASK
(
   `ID` varchar(36) NOT NULL COMMENT '主键ID',
   `NAME` varchar(50) DEFAULT NULL COMMENT '调度任务名称',
   `URL` varchar(2083) DEFAULT NULL COMMENT '路由',
   `ACTION_TYPE` int(11) DEFAULT NULL COMMENT '路由ACTION 类型',
   `TYPE` int(11) DEFAULT NULL COMMENT '单次型任务：0；重复型任务：1',
   `DATE_TYPE` int(11) DEFAULT NULL COMMENT '时间类型：天|周|月|年',
   `CONTENT` varchar(2000) DEFAULT NULL COMMENT '调度配置内容',
   `RULE` varchar(50) DEFAULT NULL COMMENT '时间类型：天|周|月|年',
   `STATE` int(11) DEFAULT NULL,
   `SORT` int(11) DEFAULT NULL,
   `ADD_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务调度';


/*组件模板分组表*/
CREATE TABLE DT_COMPONENT_TEMPLATE_GROUP
(
   `ID` varchar(36) NOT NULL COMMENT '主键ID',
   `NAME` varchar(50) DEFAULT NULL COMMENT '分组名称',
   `DESCR` varchar(500) DEFAULT NULL COMMENT '组件描述',
   `TYPE` int(11) DEFAULT NULL COMMENT '分组类型',
   `PID` varchar(36) DEFAULT NULL COMMENT '父级分组ID',
   `STATE` int(11) DEFAULT NULL,
   `SORT` int(11) DEFAULT NULL,
   `ADD_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='组件及模板分组表';


/*组件模板表*/
CREATE TABLE DT_COMPONENT_TEMPLATE
(
   `ID` varchar(36) NOT NULL COMMENT '主键ID',
   `NAME` varchar(50) DEFAULT NULL COMMENT '组件名称',
   `DESCR` varchar(500) DEFAULT NULL COMMENT '组件描述',
   `HTML_TEMPLATE_URL` varchar(2083) DEFAULT NULL COMMENT '组件HTML模板路径',
   `STYLE_TEMPLATE_URL` varchar(2083) DEFAULT NULL COMMENT '组件样式模板路径',
   `JS_PARAM_TEMPLATE_URL` varchar(2083) DEFAULT NULL COMMENT '组件脚本参数路径',
   `IMAGE_URL` varchar(2083) DEFAULT NULL COMMENT '组件效果图片路径',
   `GROUP_ID` varchar(36) DEFAULT NULL COMMENT '分组ID',
   `STATE` int(11) DEFAULT NULL,
   `SORT` int(11) DEFAULT NULL,
   `ADD_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='组件及模板表';


select version();